version: "3"
services:
 mysql:
  image: mysql
  ports:
   - "3307:3306"
  environment:
   MYSQL_ROOT_PASSWORD: supersecret
  volumes:
   - ./test_db:/docker-entrypoint-initdb.d
 web:
  build: web/
  ports:
   - "3000:3000"
  links:
   - mysql
  depends_on:
   - mysql
